version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: CardsPostgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: CardsRedis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: